blueprint:
  name: "Electricity tariffs"
  description: "Electricity price tariffs based on time bands. Before setting up the automation, create a unit meter for each device you'd like to track, with F1, F2 and F3 tariffs, and three helpers with the cost for the Peak, Standard and Off-peak hours tariffs."
  source_url: https://github.com/giovdi/ha-prices/edit/main/home_tariffe.yaml
  domain: automation

  input:
    tariff_entities:
      name: "Unit meters to automate"
      description: "Select all the Unit meters to automate"
      default: []
      selector:
        entity:
          multiple: true
          filter:
            domain: unit_meter
          
mode: restart
max_exceeded: silent
      
## time：
## F1（08-19)
## F2（mon 07-08, 19-23 - sat 07-23)
## F3（mon-sat 00-07, 23-24 - sun 00-24)
trigger:
  - platform: time
    at: "00:00:00"
    id: "t_slot_a1"
  - platform: time
    at: "07:00:00"
    id: "t_slot_a2"
  - platform: time
    at: "08:00:00"
    id: "t_slot_a3"
  - platform: time
    at: "19:00:00"
    id: "t_slot_a4"
  - platform: time
    at: "23:00:00"
    id: "t_slot_a5"
action:
  - if:
      - condition: trigger
        id:
          - "t_slot_a1"
    then:
      - service: select.select_option
        target:
          entity_id: !input tariff_entities
        data:
          option: F3
      - service: select.select_option
        target:
          entity_id: input_select.tariff_current_band
        data:
          option: F3
        
  - if:
      - condition: trigger
        id:
          - "t_slot_a2"
      - condition: time
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
        - sat
    then:
      - service: select.select_option
        target:
          entity_id: !input tariff_entities
        data:
          option: F2
      - service: select.select_option
        target:
          entity_id: input_select.tariff_current_band
        data:
          option: F2
        
  - if:
      - condition: trigger
        id:
          - "t_slot_a3"
      - condition: time
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    then:
      - service: select.select_option
        target:
          entity_id: !input tariff_entities
        data:
          option: F1
      - service: select.select_option
        target:
          entity_id: input_select.tariff_current_band
        data:
          option: F1
        
  - if:
      - condition: trigger
        id:
          - "t_slot_a4"
      - condition: time
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    then:
      - service: select.select_option
        target:
          entity_id: !input tariff_entities
        data:
          option: F2
      - service: select.select_option
        target:
          entity_id: input_select.tariff_current_band
        data:
          option: F2
        
  - if:
      - condition: trigger
        id:
          - "t_slot_a5"
      - condition: time
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
        - sat
    then:
      - service: select.select_option
        target:
          entity_id: !input tariff_entities
        data:
          option: F3
      - service: select.select_option
        target:
          entity_id: input_select.tariff_current_band
        data:
          option: F3
