blueprint:
  name: "Electricity tariffs"
  description: "Electricity price tariffs"
  source_url: https://github.com/giovdi/ha-prices/edit/main/home_tariffe.yaml
  domain: automation
  input:
    tariff_f1:
      name: "F1 tariff amount"
      description: "High peak tarif"
      default: 0.20
      selector:
        number:
          min: 0.0
          max: 3.0
          unit_of_measurement: "EUR"
          step: 0.01
          mode: slider
    tariff_f2:
      name: "F2 tariff amount"
      description: "Mid peak tarif"
      default: 0.20
      selector:
        number:
          min: 0.0
          max: 3.0
          unit_of_measurement: "EUR"
          step: 0.01
          mode: slider
    tariff_f3:
      name: "F3 tariff amount"
      description: "Low peak tarif"
      default: 0.20
      selector:
        number:
          min: 0.0
          max: 3.0
          unit_of_measurement: "EUR"
          step: 0.01
          mode: slider

mode: restart
max_exceeded: silent

variables:
  tariff_f1: !input tariff_f1
  tariff_f2: !input tariff_f2
  tariff_f3: !input tariff_f3

  tariff_price_current: >-
    {% if is_state('select.daily_energy', 'F1') %}
      {{ tariff_f1 }}
    {% elif is_state('select.daily_energy', 'F2') %}
      {{ tariff_f2 }}
    {% elif is_state('select.daily_energy', 'F3') %}
      {{ tariff_f3 }}
    {% else %}
      0
    {% endif %}
    
utility_meter:
  meter_energy_daily:
    source: sensor.meter_importenergy
    cycle: daily
  meter_energy_monthly:
    source: sensor.meter_importenergy
    cycle: monthly
  daily_energy:
    source: sensor.meter_importenergy
    name: Daily Energy
    cycle: daily
    tariffs:
      - F1
      - F2
      - F3
  monthly_energy:
    source: sensor.meter_importenergy
    name: Monthly Energy
    cycle: monthly
    tariffs:
      - F1
      - F2
      - F3
      
## time：
## F1（08-19)
## F2（mon 07-08, 19-23 - sat 07-23)
## F3（mon-sat 00-07, 23-24 - sun 00-24)
automation:
  trigger:
    - platform: time
      at: "00:00:00"
      variables:
        tariff: "F3"
    - platform: time
      at: "07:00:00"
      variables:
        tariff: "F2"
    - platform: time
      at: "08:00:00"
      variables:
        tariff: "F1"
    - platform: time
      at: "19:00:00"
      variables:
        tariff: "F2"
    - platform: time
      at: "23:00:00"
      variables:
        tariff: "F3"
  condition:
      condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    - service: select.select_option
      target:
        entity_id: select.daily_energy
      data:
        option: "{{ tariff }}"
    - service: select.select_option
      target:
        entity_id: select.monthly_energy
      data:
        option: "{{ tariff }}"
automation:
  trigger:
    - platform: time
      at: "00:00:00"
      variables:
        tariff: "F3"
    - platform: time
      at: "07:00:00"
      variables:
        tariff: "F2"
    - platform: time
      at: "23:00:00"
      variables:
        tariff: "F3"
  condition:
      condition: time
      weekday:
      - sat
  action:
    - service: select.select_option
      target:
        entity_id: select.daily_energy
      data:
        option: "{{ tariff }}"
    - service: select.select_option
      target:
        entity_id: select.monthly_energy
      data:
        option: "{{ tariff }}"
automation:
  trigger:
    - platform: time
      at: "00:00:00"
      variables:
        tariff: "F3"
  condition:
      condition: time
      weekday:
      - sun
  action:
    - service: select.select_option
      target:
        entity_id: select.daily_energy
      data:
        option: "{{ tariff }}"
    - service: select.select_option
      target:
        entity_id: select.monthly_energy
      data:
        option: "{{ tariff }}"
