blueprint:
  name: "Electricity tariffs"
  description: "Electricity price tariffs based on time bands"
  source_url: https://github.com/giovdi/ha-prices/edit/main/home_tariffe.yaml
  domain: automation

  input:
    tariff_f1:
      name: F1 tariff amount
      description: Peak hours tariff
      default: 0.20
      selector:
        number:
          min: 0.0
          max: 3.0
          unit_of_measurement: EUR
          step: 0.01
          mode: slider
    tariff_f2:
      name: F2 tariff amount
      description: Standard hours tariff
      default: 0.20
      selector:
        number:
          min: 0.0
          max: 3.0
          unit_of_measurement: EUR
          step: 0.01
          mode: slider
    tariff_f3:
      name: F3 tariff amount
      description: Off-peak hours tariff
      default: 0.20
      selector:
        number:
          min: 0.0
          max: 3.0
          unit_of_measurement: EUR
          step: 0.01
          mode: slider
          
mode: restart
max_exceeded: silent

variables:
  tariff_f1: !input tariff_f1
  tariff_f2: !input tariff_f2
  tariff_f3: !input tariff_f3

  tariff_price_current: >-
    {% if is_state('select.daily_energy', 'F1') %}
      {{ tariff_f1 }}
    {% elif is_state('select.daily_energy', 'F2') %}
      {{ tariff_f2 }}
    {% elif is_state('select.daily_energy', 'F3') %}
      {{ tariff_f3 }}
    {% else %}
      0
    {% endif %}
      
## time：
## F1（08-19)
## F2（mon 07-08, 19-23 - sat 07-23)
## F3（mon-sat 00-07, 23-24 - sun 00-24)
trigger:
  - platform: time
    at: "00:00:00"
    id: "t_slot_a1"
  - platform: time
    at: "07:00:00"
    id: "t_slot_a2"
  - platform: time
    at: "08:00:00"
    id: "t_slot_a3"
  - platform: time
    at: "19:00:00"
    id: "t_slot_a4"
  - platform: time
    at: "23:00:00"
    id: "t_slot_a5"
action:
  - if:
      - condition: trigger
        id:
          - "t_slot_a1"
    then:
      service: select.select_option
      target:
        entity_id: select.daily_energy
      data:
        option: F3
        
  - if:
      - condition: trigger
        id:
          - "t_slot_a2"
      - condition: time
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
        - sat
    then:
      service: select.select_option
      target:
        entity_id: select.daily_energy
      data:
        option: F2
        
  - if:
      - condition: trigger
        id:
          - "t_slot_a3"
      - condition: time
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    then:
      service: select.select_option
      target:
        entity_id: select.daily_energy
      data:
        option: F1
        
  - if:
      - condition: trigger
        id:
          - "t_slot_a4"
      - condition: time
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    then:
      service: select.select_option
      target:
        entity_id: select.daily_energy
      data:
        option: F2
        
  - if:
      - condition: trigger
        id:
          - "t_slot_a5"
      - condition: time
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
        - sat
    then:
      service: select.select_option
      target:
        entity_id: select.daily_energy
      data:
        option: F3
