
sensor:
  - platform: template
    sensors:
      energy_price_f1:
        friendly_name: "F1"
        value_template: "0.20"
        icon_template: mdi:speedometer
        unit_of_measurement: "EUR"
      energy_price_f2:
        friendly_name: "F2"
        value_template: "0.20"
        icon_template: mdi:speedometer-medium
        unit_of_measurement: "EUR"
      energy_price_f3:
        friendly_name: "F3"
        value_template: "0.20"
        icon_template: mdi:speedometer-slow
        unit_of_measurement: "EUR"
      energy_price_current: 
        friendly_name: "Fascia corrente"
        value_template: >-
          {% if is_state('select.daily_energy', 'F1') %}
            {{(states('sensor.energy_price_f1'))}}
          {% elif is_state('select.daily_energy', 'F2') %}
            {{(states('sensor.energy_price_f2'))}}
          {% elif is_state('select.daily_energy', 'F3') %}
            {{(states('sensor.energy_price_f3'))}}
          {% else %}
            0
          {% endif %}
        icon_template: >-
          {% if is_state('select.daily_energy', 'F1') %}
            mdi:speedometer
          {% elif is_state('select.daily_energy', 'F2') %}
            mdi:speedometer-medium
          {% elif is_state('select.daily_energy', 'F3') %}
            mdi:speedometer-slow
          {% else %}
            mdi:exclamation-thick
          {% endif %}
        unit_of_measurement: "EUR"
      daily_energy_f3_money:
        unit_of_measurement: "EUR"
        value_template: "{{ ( states('sensor.daily_energy_f3')|float * states('sensor.energy_price_current')|float ) | round(2) }}"
      daily_energy_f2_money:
        unit_of_measurement: "EUR"
        value_template: "{{ ( states('sensor.daily_energy_f2')|float * states('sensor.energy_price_current')|float ) | round(2) }}"
      daily_energy_f1_money:
        unit_of_measurement: "EUR"
        value_template: "{{ ( states('sensor.daily_energy_f1')|float * states('sensor.energy_price_current')|float ) | round(2) }}"
      monthly_energy_f3_money:
        unit_of_measurement: "EUR"
        value_template: "{{ ( states('sensor.monthly_energy_f3')|float * states('sensor.energy_price_current')|float ) | round(2) }}"
      monthly_energy_f2_money:
        unit_of_measurement: "EUR"
        value_template: "{{ ( states('sensor.monthly_energy_f2')|float * states('sensor.energy_price_current')|float ) | round(2) }}"
      monthly_energy_f1_money:
        unit_of_measurement: "EUR"
        value_template: "{{ ( states('sensor.monthly_energy_f1')|float * states('sensor.energy_price_current')|float ) | round(2) }}"
      meter_energy_daily_money:
        unit_of_measurement: "EUR"
        value_template: "{{ (states('sensor.daily_energy_f3_money')) + (states('sensor.daily_energy_f2_money')) + (states('sensor.daily_energy_f1_money')) }}"
      meter_energy_monthly_money:
        unit_of_measurement: "EUR"
        value_template: "{{ (states('sensor.monthly_energy_f3_money')) + (states('sensor.monthly_energy_f2_money')) + (states('sensor.monthly_energy_f1_money')) }}"
utility_meter:
  meter_energy_daily:
    source: sensor.meter_importenergy
    cycle: daily
  meter_energy_monthly:
    source: sensor.meter_importenergy
    cycle: monthly
  daily_energy:
    source: sensor.meter_importenergy
    name: Daily Energy
    cycle: daily
    tariffs:
      - F1
      - F2
      - F3
  monthly_energy:
    source: sensor.meter_importenergy
    name: Monthly Energy
    cycle: monthly
    tariffs:
      - F1
      - F2
      - F3
## time：
## F1（08-19)
## F2（mon 07-08, 19-23 - sat 07-23)
## F3（mon-sat 00-07, 23-24 - sun 00-24)
automation:
  trigger:
    - platform: time
      at: "00:00:00"
      variables:
        tariff: "F3"
    - platform: time
      at: "07:00:00"
      variables:
        tariff: "F2"
    - platform: time
      at: "08:00:00"
      variables:
        tariff: "F1"
    - platform: time
      at: "19:00:00"
      variables:
        tariff: "F2"
    - platform: time
      at: "23:00:00"
      variables:
        tariff: "F3"
  condition:
      condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    - service: select.select_option
      target:
        entity_id: select.daily_energy
      data:
        option: "{{ tariff }}"
    - service: select.select_option
      target:
        entity_id: select.monthly_energy
      data:
        option: "{{ tariff }}"
automation:
  trigger:
    - platform: time
      at: "00:00:00"
      variables:
        tariff: "F3"
    - platform: time
      at: "07:00:00"
      variables:
        tariff: "F2"
    - platform: time
      at: "23:00:00"
      variables:
        tariff: "F3"
  condition:
      condition: time
      weekday:
      - sat
  action:
    - service: select.select_option
      target:
        entity_id: select.daily_energy
      data:
        option: "{{ tariff }}"
    - service: select.select_option
      target:
        entity_id: select.monthly_energy
      data:
        option: "{{ tariff }}"
automation:
  trigger:
    - platform: time
      at: "00:00:00"
      variables:
        tariff: "F3"
  condition:
      condition: time
      weekday:
      - sun
  action:
    - service: select.select_option
      target:
        entity_id: select.daily_energy
      data:
        option: "{{ tariff }}"
    - service: select.select_option
      target:
        entity_id: select.monthly_energy
      data:
        option: "{{ tariff }}"